Channel aware Product Primary Collection
Pinelab-studio/pinelab-vendure-plugins pull request #461
Opened 2024-07-03 20:10 UTC by dalyathan

# Description

The changes in this PR implement and close #456 
# Breaking changes

The collection field `Product.customFields.primaryCollection` now has type `[String!]`
# Screenshots

<img width="1470" alt="channel-1" src="https://github.com/Pinelab-studio/pinelab-vendure-plugins/assets/39517388/0cdb844f-f36a-41b6-867f-dabdb3e6b618">
<img width="1468" alt="channel-2" src="https://github.com/Pinelab-studio/pinelab-vendure-plugins/assets/39517388/fbce17d4-db14-4d77-b3ac-c0ec03bc6520">

# Checklist

📌 Always:
- [X] I have set a clear title
- [X] My PR is small and contains a single feature
- [X] I have [checked my own PR](## "Fix typo's and remove unused or commented out code")

👍 Most of the time:
- [X] I have added or updated test cases for important functionality
- [ ] I have updated the README if needed

📦 For publishable packages:
- [X] I have [increased the version number](## "After increasing the version to the next patch/minor/major, the package will be published automatically after merge") in `package.json`
- [X] I have added my changes to the `CHANGELOG.md` [See this example](https://github.com/Pinelab-studio/pinelab-vendure-plugins/blob/main/packages/vendure-plugin-invoices/CHANGELOG.md)

2024-07-03 21:02 UTC, dalyathan commented on packages/vendure-plugin-primary-collection/src/api/primary-collection.resolver.ts
> +    return collection.channels;
why do we need to reverse the order of the decorators?

2024-07-05 10:09 UTC, martijnvdbrug requested changes
Impressive and clean solution :ok_hand: There is a bit of a performance hit when we load a big list of products + primary collections, because we do an extra DB call per primary collection. But I think there is no other way. And we will just test it out to see if it really matters.

I  do have some requested changes still:

* Can you make this a breaking change (major version)? A DB migration is needed, which looses all the currently set primary collections. 
* Is there any way we can migrate? For example, how would we install this plugin in the CG project, without loosing all the configured primary collections? It would be nice to have a script included that exports all the currently set primary collections to a JSON file, and then another script to insert them again.
* Can you also extend the graphql Product type with a field `breadcrumbs: CollectionBreadcrumb`? Same as a Collection. Because we have a primary collection, we can now resolve the breadcrumb of a product :smile: . It would prepend the id/name/slug of the product to the already existing breadcrumb of the primary collection.
* Would it make more sense to have the customField to be a `string` and put the entire JSON array in there? E.g. `[{"channelId":"1","collectionId":"5"}]`, instead of multiple strings of 1 JSON object. I did it this way (with `string[]`) in the CG configurator options as well, but I regret that decision... As a dev it's a bit easier to just be able to copy the entire custom field as JSON, instead of parsing each entry of an array. WDYT?
* Minor point: should we rename `getCandidatePrimaryCollections` to `getEligiblePrimaryCollections` to stay in line with Vendure's terminology?

2024-07-12 09:44 UTC, dalyathan commented on packages/vendure-plugin-primary-collection/src/util/export-primary-collections.ts
> +    await fs.writeFile(EXPORTED_PRIMARY_COLLECTIONS_FILE, jsonString);
The directory will be the current directory, wherever it is

2024-07-12 09:45 UTC, dalyathan commented on packages/vendure-plugin-primary-collection/src/api/primary-collection.resolver.ts
> +  @Resolver('Product')
This won't work

2024-07-12 09:45 UTC, dalyathan commented on packages/vendure-plugin-primary-collection/src/api/primary-collection.resolver.ts
>      @Ctx() ctx: RequestContext,
This won't work too

2024-07-18 12:46 UTC, martijnvdbrug approved these changes
Approved, nice work! I will create a task to test out the migration on the CG project. I've added 1 commit to also resolve the parent collection breadcrumb for the product:

https://github.com/Pinelab-studio/pinelab-vendure-plugins/pull/461/commits/b08cd0b02163c60f02eb473a041b8b422aac3a30

This should make it easier to create breadcrumbs on the storefront

![image](https://github.com/user-attachments/assets/5f43c678-769c-4708-9bc5-3a8efca5163d)

2024-07-18 12:53 UTC, merged